

import mongoose from 'mongoose';

const appointmentSchema = new mongoose.Schema(
  {
    serviceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Service',
      required: true,
    },

    name: {
      type: String,
      required: [true, 'Customer name is required'],
      trim: true,
    },

    email: {
      type: String,
      required: [true, 'Email is required'],
      lowercase: true,
      trim: true,
    },

    bookedFor: {
      type: Date,
      required: [true, 'Booking datetime is required'],
      // Stores the exact datetime: 2026-04-16T18:00:00.000Z
      // This is what we check against for conflicts
    },

    status: {
      type: String,
      enum: ['CONFIRMED', 'CANCELLED'],
      default: 'CONFIRMED',
    },

    refCode: {
      type: String,
      unique: true,
      required: true,
      // e.g., "APT-7K3X" — generated by refCodeGenerator
    },
  },
  {
    timestamps: true, // createdAt for audit, updatedAt for cancel tracking
  }
);

// Index for duplicate detection:
// "Does this person already have a booking at this exact time?"
appointmentSchema.index({ email: 1, bookedFor: 1 });

// Index for admin queries: filter by status + date
appointmentSchema.index({ status: 1, bookedFor: 1 });

const Appointment = mongoose.model('Appointment', appointmentSchema);
export default Appointment;
